### ISSUE TITLE
LOGIN] Failed to login TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by onesyah05** [junhoyeo/threads-api#165]
i can't publish

![image](https://github.com/junhoyeo/threads-api/assets/42487726/0ca9365f-9ffd-41dc-87fc-5dba662863a3)

[LOGIN] Failed to login TypeError: Cannot read properties of undefined (reading 'split')
    at D:\shoppe\node_modules\threads-api\build\threads-api.js:1:5064
    at D:\shoppe\node_modules\threads-api\build\threads-api.js:1:1798
    at Object.next (D:\shoppe\node_modules\threads-api\build\threads-api.js:1:1903)
    at a (D:\shoppe\node_modules\threads-api\build\threads-api.js:1:379)
    at i (D:\shoppe\node_modules\threads-api\build\threads-api.js:1:576)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ssig33** [comment]
I am also getting this error. Notably, however, I am also encountering the same error when logging in with Meta's Threads application. So I am thinking that this is not a problem with this library, but that we are temporarily banned from Threads by Meta.

(I think it can be pointed out that the current threads-api model is to log in to threads for each execution, and this can easily lead to banning. A simple mechanism to serialize login sessions and use them across executions may be required.)

**Comment by wack-overflow** [comment]
If you don't want to log in for each execution, you should persist your auth token somewhere, in a DB for example, and reuse that in future executions

**Comment by Aerglonus** [comment]
> I am also getting this error. Notably, however, I am also encountering the same error when logging in with Meta's Threads application. So I am thinking that this is not a problem with this library, but that we are temporarily banned from Threads by Meta.
> 
> (I think it can be pointed out that the current threads-api model is to log in to threads for each execution, and this can easily lead to banning. A simple mechanism to serialize login sessions and use them across executions may be required.)

As @wack-overflow said to prevent login each time you can run the code using userID and token, you can get them with `getToken` and `getUserIDfromUsername` plus you can pass device identifier and device id so it doesn't trigger the "Unauthorized login" each time you do something, this just a measure to lower the chances Instagram flags the account as compromised or spam.

**Comment by taishi55** [comment]
@Aerglonus Could you show us the code how you can login with `token` and `userId` ?

**Comment by Aerglonus** [comment]
> @Aerglonus Could you show us the code how you can login with `token` and `userId` ?

Just pass the values to client, in my case i passed some extra properties to avoid requesting new values each time and also avoid getting the account flagged as if it was compromised because of the different deviceID, so my `deviceID` its the one from my actual phone and on `device` I passed also my phone actual specifications that way Instagram thinks its login in from my already authorized phone.

> Note: the `device` and `fbLSDToken` properties are not  necessary I just use them as an extra step to not trigger any flags on Instagram side..
  ```
const threadsAPI = new ThreadsAPI({
    verbose: true,
    device: {
      manufacturer: 'your-phone-manufacturer',
      model: 'your-phone-model',
      os_version: android-version,
      os_release: 'phone-os-version',
    },
    fbLSDToken: 'redacted',
    noUpdateLSD: true,
    token: 'redacted', // Your token
    deviceID: 'android-redacted', // Your device ID
    userID: 'redacted'
  });
```

**Comment by aruballo** [comment]
For those who were having problems finding some of these values, I used an app called Device Info on the Google play store to get the device ID. The rest should be easily available in the settings (model, os version, etc.)

**Comment by taishi55** [comment]
@Aerglonus I tried your approach, but didn't work for me. Here is the code.

```ts
const threadsAPI = new ThreadsAPI({
			verbose: true,
			noUpdateLSD: true,
			token,
			userID
		});
const user = await threadsAPI.getUserProfile(userID);
```

The result: 
```
TypeError: Cannot read properties of undefined (reading 'userData')
    at a.<anonymous> (/Users/taishi/Desktop/threads-engagement-app/node_modules/threads-api/build/threads-api.js:1:9626)
    at /Users/taishi/Desktop/threads-engagement-app/node_modules/threads-api/build/threads-api.js:1:1769
    at Object.next (/Users/taishi/Desktop/threads-engagement-app/node_modules/threads-api/build/threads-api.js:1:1874)
    at a (/Users/taishi/Desktop/threads-engagement-app/node_modules/threads-api/build/threads-api.js:1:350)
    at i (/Users/taishi/Desktop/threads-engagement-app/node_modules/threads-api/build/threads-api.js:1:547)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Aerglonus** [comment]
> @Aerglonus I tried your approach, but didn't work for me. Here is the code.
> 
> ```ts
> const threadsAPI = new ThreadsAPI({
> 			verbose: true,
> 			noUpdateLSD: true,
> 			token,
> 			userID
> 		});
> const user = await threadsAPI.getUserProfile(userID);
> ```
> 
> The result:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'userData')
>     at a.<anonymous> (/node_modules/threads-api/build/threads-api.js:1:9626)
>     at /node_modules/threads-api/build/threads-api.js:1:1769
>     at Object.next (/node_modules/threads-api/build/threads-api.js:1:1874)
>     at a (/node_modules/threads-api/build/threads-api.js:1:350)
>     at i (/node_modules/threads-api/build/threads-api.js:1:547)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

This could be related to what i was seeing recently, when using `getToken` that returns the `userID` as undefined this is a new issue related to the data that comes back from Threads
