### ISSUE TITLE
login not work

### ISSUE THREAD

**Issue by kostyaavdonin** [junhoyeo/threads-api#212]
i'm update u library from latest version.

Error: Login Failed
    at /home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:6175
    at /home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:2620
    at Object.next (/home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:2725)
    at i (/home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:481)
    at o (/home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:678)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
      const threadsAPI = new ThreadsAPI({
                    username: context.scene.state.login,
                    password: context.scene.state.password,
                    deviceID: `android-${(Math.random() * 1e24).toString(36)}`,
                    httpAgent: agent
                });

**Comment by kostyaavdonin** [comment]
found a solution - you need to go into the application itself and confirm the entry.

you need to be in the application itself. otherwise confirmation will not come.

**Comment by junhoyeo** [comment]
Are you using 2FA?

**Comment by kostyaavdonin** [comment]
> Are you using 2FA? 

No.
